import = [
    "~/.config/alacritty/alacritty-theme/themes/ayu_dark.toml"
]


[window]
padding.x = 10
padding.y = 10
opacity = 0.75
blur =false 

decorations = "Transparent"

[font]
normal.family = "Fira Code"

#regular
size = 16

#for video
# size = 35.0
