import = [
    "~/.config/alacritty/alacritty-theme/themes/ayu_dark.toml"
]


[window]
padding.x = 10
padding.y = 10
opacity = 0.75
blur = true

decorations = "Full"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16

#for video
# size = 35.0
